import { Link } from 'react-router-dom';
import { Upload, ArrowRight, ShieldCheck, Brain, Database, Monitor } from 'lucide-react';

export default function AboutPage() {
  return (
    <div className="animate-fade-in">
      {/* Hero */}
      <section className="relative overflow-hidden hero-gradient">
        <div className="absolute inset-0 grid-pattern" />
        <div className="relative max-w-4xl mx-auto px-4 sm:px-6 pt-20 pb-16 sm:pt-24">
          <h1 className="font-display font-extrabold text-4xl sm:text-5xl text-ink-900 leading-tight tracking-tight text-center">
            About FlashStudy
          </h1>
          <p className="mt-6 text-lg text-ink-600 leading-relaxed text-center max-w-2xl mx-auto">
            A free, browser-based study tool that lets you use your purchased .apkg flashcard decks
            without installing any software or creating an account.
          </p>
        </div>
      </section>

      {/* What is it */}
      <section className="max-w-4xl mx-auto px-4 sm:px-6 py-16">
        <div className="prose prose-lg max-w-none">
          <h2 className="font-display font-bold text-2xl text-ink-900 mb-4">What is FlashStudy?</h2>
          <p className="text-ink-600 leading-relaxed mb-6">
            FlashStudy is an online companion to our WooCommerce flashcard store. When you buy a deck,
            you get a <strong className="text-ink-900">.apkg file</strong> — the standard Anki package
            format. Instead of needing to download and install Anki on your computer, FlashStudy lets
            you open and study that file right here in your web browser.
          </p>
          <p className="text-ink-600 leading-relaxed">
            Everything happens on your device. The file is parsed in your browser, the cards are
            displayed on screen, and your study progress is saved locally — nothing is uploaded to
            any server.
          </p>
        </div>
      </section>

      {/* How it works */}
      <section className="bg-white border-y border-ink-200">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 py-16">
          <h2 className="font-display font-bold text-2xl text-ink-900 mb-8">How it works</h2>
          <div className="space-y-8">
            <HowItWorksItem
              icon={Database}
              title="1. The .apkg file format"
              desc="An .apkg file is a compressed archive containing an SQLite database with all your flashcard content — questions, answers, and metadata. FlashStudy unpacks this archive and reads the database directly in your browser using WebAssembly, so no data ever leaves your device."
            />
            <HowItWorksItem
              icon={Brain}
              title="2. Spaced repetition algorithm"
              desc="FlashStudy uses a spaced repetition system (SRS) similar to Anki's. When you review a card, you rate how well you knew it (Again, Hard, Good, or Easy). The algorithm then schedules the next review at increasing intervals based on your rating, so you see difficult cards more often and easy cards less frequently. This is the most efficient way to memorize information long-term."
            />
            <HowItWorksItem
              icon={ShieldCheck}
              title="3. Your progress stays private"
              desc="Your study progress — which cards you've reviewed, when they're due next, and your statistics — is stored in your browser's local storage. It never leaves your device. Clear your browser data and the progress resets; come back on the same browser and you pick up right where you left off."
            />
          </div>
        </div>
      </section>

      {/* Anki compatibility */}
      <section className="max-w-4xl mx-auto px-4 sm:px-6 py-16">
        <div className="p-8 rounded-2xl bg-primary-50 border border-primary-100">
          <h2 className="font-display font-bold text-xl text-ink-900 mb-4">About Anki compatibility</h2>
          <p className="text-ink-600 leading-relaxed">
            FlashStudy reads standard .apkg files generated by Anki. It supports text-based cards with
            multiple fields, tags, and multiple decks within a single file. The spaced repetition
            scheduling is compatible with Anki's SM-2 algorithm, so your review intervals will be
            similar to what you'd get in the desktop app.
          </p>
          <p className="text-ink-500 text-sm mt-4">
            FlashStudy is an independent tool and is not affiliated with, endorsed by, or connected to
            Anki or its developers. .apkg is an open file format that anyone can read and write.
          </p>
        </div>
      </section>

      {/* CTA */}
      <section className="max-w-4xl mx-auto px-4 sm:px-6 pb-20">
        <div className="flex flex-col sm:flex-row items-center justify-center gap-4 p-8 rounded-2xl bg-ink-900">
          <div className="text-center sm:text-left flex-1">
            <h3 className="font-display font-bold text-xl text-white">Ready to study?</h3>
            <p className="text-ink-300 text-sm mt-1">Upload your .apkg file and get started now.</p>
          </div>
          <Link
            to="/study"
            className="inline-flex items-center gap-2 px-6 py-3 rounded-xl bg-white text-ink-900 font-semibold hover:bg-ink-100 transition-all whitespace-nowrap"
          >
            Go to Study
            <ArrowRight className="w-4 h-4" />
          </Link>
        </div>
      </section>
    </div>
  );
}

function HowItWorksItem({ icon: Icon, title, desc }: { icon: typeof Upload; title: string; desc: string }) {
  return (
    <div className="flex gap-5">
      <div className="flex-shrink-0 w-12 h-12 rounded-xl bg-primary-50 flex items-center justify-center">
        <Icon className="w-6 h-6 text-primary-600" />
      </div>
      <div>
        <h3 className="font-display font-bold text-lg text-ink-900 mb-2">{title}</h3>
        <p className="text-ink-600 leading-relaxed">{desc}</p>
      </div>
    </div>
  );
}
